import random
import time

def displayfirst():
    print("Very well then", name, "you currently have", coins,"coins and", health ,"health, let us start our journey!")
    time.sleep(4)
    print("CHAPTER ONE: Departure")
    time.sleep(5)
    print("As you leave the kingdom of Bobotroyia you can't help but notice and hear a faint sound hustling behind you.")
    time.sleep(6)
    print("As you look back, you see a figure in the distance that seems to be shouting at you..")
    time.sleep(5)
    print("")
    print("It was your friend, Leomarc")
    print("")
    time.sleep(3)
    print("Leomarc: Hey", name, "be safe on your trip!")
    print("")
    time.sleep(6)
    print("Seeing as you've probably already walked too far from the gates, you decided to just wave your hands toward your friend.")
    time.sleep(6)
    print("While waving your final goodbyes you decided to stop as you were mesmerized by the view of Bobotroyia from the outside world...")
    time.sleep(6)
    print("The view of the diamond castle atop the kingdom reflecting the rays of the sun in all directions as if mimicking a lamp in a dark room")
    time.sleep(6)
    print("except the room that this lamp occupies is none other than the vast vallies and mountains surrounding it")
    time.sleep(5)
    print("But what struck your heart most was the view of the people living in the kingdom, merrily doing their daily tasks, happily singing their joyous hymns.")
    time.sleep(6)
    print("The people in the kingdom, the people....")
    time.sleep(3)
    print("")
    time.sleep(3)
    print("you were once a part of.")
    print("")
    time.sleep(5)
    print("Who would've thought that you", name,"the Great would one day be excommunicated from the one kingdom you yourself saved?")
    time.sleep(7)
    print("'But what is past is a part of the past' you say to yourself as you notice the goblin behind the tree hiding as if waiting for a chance to assassinate you")
    print("")
    time.sleep(7)
    print("You've dealt with this a lot what do you want to do?")
    time.sleep(4)
    print("")
    print("Input '1' to walk towards the tree and fight the goblin head on")
    print("Input '2' to act like you don't know and wait for the goblin to come out")
    print("Input '3' if you want to kill yourself")
    print("")
def choosepath1():
    path = ""
    while path!="1" and path!="2" and path!="3":
        path = input("Input 1 or 2, don't kill yourself: ")
    return path
def checkpath1(choosepath1):
    if choosepath1 == "3":
        print("")
        print("Are you actually kidding me?")
        time.sleep(3)
        print("I didn't spend all this day coding")
        time.sleep(3)
        print("Just for the player to die in chapter one")
        time.sleep(2)
        print(" CHAPTER FREKNIG O N E ")
        time.sleep(5)
        print("You died. the end haha very funny")
        time.sleep(5)
        print("Just kidding, you became friends with the goblin his name is Gabgab")
        print("and during the conversation the player knows about his/her character's past")
        print("WHICH YOU dOnT kNoW NOW CAUSE YOU CHOSE TO TAKE THIS PATH, sIKE BITCH!")
        print("")
    elif choosepath1 == "2":
        print("")
        print("You stand still while watching the goblin as casually as you can..")
        time.sleep(4)
        print("After waiting a few minutes you noticed that the goblin decided to make its move")
        time.sleep(5)
        print("It showed itself as vulnerable as it can")
        time.sleep(3)
        print("and....")
        print("")
        time.sleep(3)
        print("talked?")
        print("")
        time.sleep(3)
        print("$@#!#: Human! no.. what you?!?! you no smell like human but monstery!")
        time.sleep(4)
        print("You: ''A goblin capable of speech? huh.. weird.'' Well.. ")
        time.sleep(5)
        print("You: I've fought thousands of beasts and have stained my heart and soul with their blood.")
        time.sleep(5)
        print("You: I don't blame you for mistaking me as a monster, uhmm.. goblin? What brings you here near the outskirts of a kingdom?")
        time.sleep(5)
        print("$@#!#: Hey me name no goblin and i no goblin, call me Gabgab! I here to look for peace place")
        time.sleep(4)
        print("Gabgab: I quit goblin tribe they dumb creature and expel me for me magic!")
        time.sleep(5)
        print("You: WHAT? Gabgab.. what do you mean.. 'magic'?")
        time.sleep(5)
        print("")
        print("Gabgab: This!!")
        print("")
        time.sleep(4)
        print("The goblin in front of you, Gabgab, instantly vanishes from your sight. You reach out to try and grab him from the spot where he once was")
        print("but you are dumbfounded as you felt nothing... as if Gabgab vanished from existence.")
        print("")
        time.sleep(12)
        print("Gabgab: HA! you see?")
        time.sleep(3)
        print("You: ''A goblin capable of both speech and magic? what intelligence for a creature''")
        time.sleep(5)
        print("You: Say, Gabgab, I've recently been excommunicated from my own human kingdom and I wouldn't mind it if you tagged along.")
        time.sleep(6)
        print("Gabgab: Really? THAT GREAT! THANK THANK!")
        time.sleep(5)
        print("Seeing the goblin's ability of absolute invisibility, you became reassured that Gabgab really meant no harm towards you")
        time.sleep(6)
        print("and he probably hid behind the tree because of fear...")
        print("")
        time.sleep(5)
        print("fear from your monstrous aura.")
        time.sleep(4)
        print("")
        print("And so, with a goblin by your side you then proceed to continue your journey to utmost nowhere....")
        time.sleep(5)
        print("")
        print("for now.")
    elif choosepath1 == "1":
        print("")
        print("You casually walk towards the tree acting vulnerable")
        time.sleep(4)
        print("As you approach the tree the goblin readies itself and begins....")
        time.sleep(5)
        print("")
        print("talking?")
        print("")
        time.sleep(3)
        print("$@#!#: Human! no.. what you?!?! you no smell like human but monstery!")
        time.sleep(4)
        print("You: ''A goblin capable of speech? huh.. weird.'' Well.. ")
        time.sleep(5)
        print("You: I've fought thousands of beasts and have stained my heart and soul with their blood.")
        time.sleep(5)
        print("You: I don't blame you for mistaking me as a monster, uhmm.. goblin? What brings you here near the outskirts of a kingdom?")
        time.sleep(5)
        print("$@#!#: Hey me name no goblin and i no goblin, call me Gabgab! I here to look for peace place")
        time.sleep(4)
        print("Gabgab: I quit goblin tribe they dumb creature and expel me for me magic!")
        time.sleep(5)
        print("You: WHAT? Gabgab.. what do you mean.. 'magic'?")
        time.sleep(5)
        print("")
        print("Gabgab: This!!")
        print("")
        time.sleep(4)
        print("The goblin in front of you, Gabgab, instantly vanishes from your sight. You reach out to try and grab him from the spot where he once was")
        print("but you are dumbfounded as you felt nothing... as if Gabgab vanished from existence.")
        print("")
        time.sleep(12)
        print("Gabgab: HA! you see?")
        time.sleep(3)
        print("You: ''A goblin capable of both speech and magic? what intelligence for a creature''")
        time.sleep(5)
        print("You: Say, Gabgab, I've recently been excommunicated from my own human kingdom and I wouldn't mind it if you tagged along.")
        time.sleep(6)
        print("Gabgab: Really? THAT GREAT! THANK THANK!")
        time.sleep(5)
        print("Seeing the goblin's ability of absolute invisibility, you became reassured that Gabgab really meant no harm towards you")
        time.sleep(6)
        print("and he probably hid behind the tree because of fear...")
        print("")
        time.sleep(5)
        print("fear from your monstrous aura.")
        time.sleep(4)
        print("")
        print("And so, with a goblin by your side you then proceed to continue your journey to utmost nowhere....")
        time.sleep(5)
        print("")
        print("for now.")
def displaysecond():
    print("")
    print("CHAPTER TWO: Helplessness")
    time.sleep(5)
    print("Looking for a peaceful place, you've been wandering for hours with your goblin companion, Gabgab, through the forests")
    time.sleep(5)
    print("You get slightly surprised as Gabgab impulsively calls out to you")
    print("")
    time.sleep(4)
    print("Gabgab: HEY! human u no fair!")
    time.sleep(3)
    print("You: huh?")
    time.sleep(2)
    print("Gabgab: I tell you me Gabgab but you no tell me you?")
    time.sleep(3)
    print("You: Oh, you mean my name?")
    time.sleep(3)
    print("Gabgab: YES!")
    time.sleep(3)
    print("You: My name is", name,"and as of now I am nothing but a person venturing randomly across the lands")
    time.sleep(4)
    print("Gabgab: Cool! Hey",name,"are you me friend friend?")
    time.sleep(4)
    print("You: Friends huh....")
    time.sleep(5)
    print("You: Sure.")
    time.sleep(4)
    print("")
    print("It's becoming dark and you notice that you have already ventured far..")
    time.sleep(4)
    print("far enough that you no longer see the kingdom of Bobotroyia")
    time.sleep(4)
    print("You called out to Gabgab, telling him that you two should start to set camp for the night")
    time.sleep(5)
    print("")
    print("You: Gabgab, it is becoming dark and I suggest that we shall start talking about how we spend the night")
    time.sleep(4)
    print("You: seeing as we are in the middle of the forest, it would be dangerous when night time comes.")
    time.sleep(4)
    print("Gabgab: O K but where sleep what you want me do?")
    print("")
    time.sleep(4)
    print("As Gabgab questions you on what to do, you notice a big tree with branches large enough to be a bed")
    time.sleep(4)
    print("and a river not too far from where you are")
    time.sleep(3)
    print("")
    print("Say", name, ", what would you do?")
    print("")
    time.sleep(3)
    print("Input '1' to suggest sleeping on the tree branches")
    print("Input '2' to suggest sleeping beside the river")
    print("")
def choosepath2():
    path = ""
    while path!="1" and path!="2":
        path = input("Input 1 or 2: ")
    return path
def checkpath2(choosepath2):
    if choosepath2 == "1":
        print("You: Gabgab, see that tree over there? let's climb it and sleep on the branches")
        time.sleep(3)
        print("Gabgab: I see I see!! okay Gabgab follow")
        print("")
        time.sleep(3)
        print("As you and Gabgab climb the massive tree you take a good look at its branches and tried laying down on it")
        print("")
        time.sleep(5)
        print("You: hmmm.. Gabgab, this is good. let's sleep here for the night.")
        time.sleep(3)
        print("Gabgab: Okay! and when tomorrow come we find place peace yes?")
        time.sleep(3)
        print("You: Hmm.. yea.. sure.")
        time.sleep(2)
        print("")
        print("")
        print("As you close your eyes you seemed to find yourself entering a deep slumber and end up laying there in the tree branch")
        time.sleep(4)
        print("sound asleep.")
        time.sleep(3)
        print("")
        time.sleep(2)
        print("")
        time.sleep(2)
        print("You then wake up as you hear a loud screeching and roaring from the skies")
        time.sleep(4)
        print("You crawl up towards the upper branches of the tree and take a peek")
        time.sleep(4)
        print("In front of you is the sight of a wyvern that seems to have just finished passing by where you were")
        time.sleep(5)
        print("You can see Gabgab beside you, awake, shivering from fear")
        print("")
        time.sleep(4)
        print("Gabgab(whispering):",name," good thing we sleep here, tree leaves give us shade")
        time.sleep(4)
        print("")
        print("You heard Gabgab whisper to you, yet you didn't reply")
        time.sleep(4)
        print("You didn't reply because you were speechless..")
        time.sleep(4)
        print("Your mind is filled with nothing but the thought of...")
        time.sleep(5)
        print("")
        print("Why is a wyvern heading towards the kingdom?")
        print("")
        time.sleep(5)
        print("Confused, you instinctively started to sprint hard towards the kingdom")
        time.sleep(4)
        print("")
        print("running..")
        time.sleep(3)
        print("running..")
        time.sleep(3)
        print("You continue running without giving care to the goblin dashing behind you, with you, trying to keep up with your speed")
        time.sleep(6)
        print("")
        print("Sprinting quickly, you've finally reached the mountain ranges bordering the kingdom")
        time.sleep(5)
        print("And you were welcomed with the view of a broken lamp...")
        time.sleep(4)
        print("")
        print("You were welcomed with the view of the kingdom in shambles...")
        time.sleep(5)
        print("Wyverns infesting all across the kingdom, visibly terrorizing the people")
        time.sleep(5)
        print("And their excruciating screams of anguish reaching from where you stand..")
        time.sleep(5)
        print("")
        time.sleep(2)
        print("Seeing as you are hours away from the kingdom...")
        time.sleep(4)
        print("you start to kneel...")
        time.sleep(3)
        print("feeling helpless....")
        time.sleep(3)
        print("thinking about the people who once adored you as a hero...")
        time.sleep(4)
        print("but most importantly..")
        time.sleep(2)
        print("thinking of the highly plausible death of your best friend who continued to love you....")
        time.sleep(5)
        print("even as the kingdom shunned you out....")
        time.sleep(3)
        print("")
        print("Leomarc..")
        time.sleep(5)
        print("")
        print("With tears endlessly running down your eyes from the sight of the Kingdom currently being demolished..")
        time.sleep(4)
        print("A man carrying an instrument, with a sad and silent Gabgab behind him, calls out to you..")
        time.sleep(4)
        print("")
        print("????: I'm sorry",name,"but it's too late")
        time.sleep(3)
        print("????: I'm revered as the strongest bard on all of the lands and yet...")
        time.sleep(3)
        print("????: I could do nothing against them...")
        time.sleep(3)
        print("????: The wyverns...")
        time.sleep(3)
        print("????: there are too many of them.")
        
    elif choosepath2 == "2":
        print("You: Gabgab, see that river over there? Let's sleep beside it.")
        time.sleep(4)
        print("Gabgab: Oh.. okay okay! me follow you!")
        time.sleep(3)
        print("")
        time.sleep(2)
        print("As you and Gabgab walk over to the river you see a small lush of grass beside it")
        time.sleep(4)
        print("As you lay down on the grass, you tell Gabgab to do so as well.")
        time.sleep(3)
        print("")
        time.sleep(1)
        print("Gabgab: we sleep now?")
        time.sleep(2)
        print("You: Yes, this shall be good enough.")
        time.sleep(3)
        print("")
        time.sleep(1)
        print("You close your eyes and find yourself entering a deep slumber")
        time.sleep(4)
        print("You fall asleep.")
        time.sleep(3)
        print("")
        time.sleep(2)
        print("")
        time.sleep(1)
        print("")
        time.sleep(2)
        print("THUD!")
        time.sleep(3)
        print("You wake up to see Gabgab punching you to wake you up as he points above")
        time.sleep(4)
        print("pointing at a screeching fiery wyvern looking at you")
        time.sleep(4)
        print("You came to your senses too late as you see a fireball quickly propelling towards you")
        time.sleep(4)
        print("")
        time.sleep(1)
        print("BAM!")
        print("You lost 20 health! you only have", (health - 20), "health left.")
        print("")
        time.sleep(5)
        print("Gabgab grabs you and you start to feel light with your surroundings losing its color")
        time.sleep(4)
        print("The wyvern is confusingly looking at where you currently stand")
        time.sleep(3)
        print("But it then snaps out of its confusion and surprisingly starts to leave you and Gabgab")
        time.sleep(4)
        print("")
        print("Gabgab(whispering): me want thank for make us invisible")
        time.sleep(3)
        print("You heard Gabgab whisper to you, yet you didn't reply")
        time.sleep(4)
        print("You didn't reply because you were speechless..")
        time.sleep(4)
        print("Your mind is filled with nothing but the thought of...")
        time.sleep(5)
        print("")
        print("Why is a wyvern heading towards the kingdom?")
        print("")
        time.sleep(5)
        print("Confused, you instinctively started to sprint hard towards the kingdom")
        time.sleep(4)
        print("")
        print("running..")
        time.sleep(3)
        print("running even as you lost sight of the wyvern in front of you...")
        time.sleep(4)
        print("running..")
        time.sleep(3)
        print("You continue running without giving care to the goblin dashing behind you, with you, trying to keep up with your speed")
        time.sleep(6)
        print("")
        print("Sprinting quickly, you've finally reached the mountain ranges bordering the kingdom")
        time.sleep(5)
        print("And you were welcomed with the view of a broken lamp...")
        time.sleep(4)
        print("")
        print("You were welcomed with the view of the kingdom in shambles...")
        time.sleep(5)
        print("Wyverns infesting all across the kingdom, visibly terrorizing the people")
        time.sleep(5)
        print("And their excruciating screams of anguish reaching from where you stand..")
        time.sleep(5)
        print("")
        time.sleep(2)
        print("Seeing as you are hours away from the kingdom...")
        time.sleep(4)
        print("you start to kneel...")
        time.sleep(3)
        print("feeling helpless....")
        time.sleep(3)
        print("thinking about the people who once adored you as a hero...")
        time.sleep(4)
        print("but most importantly..")
        time.sleep(2)
        print("thinking of the highly plausible death of your best friend who continued to love you....")
        time.sleep(5)
        print("even as the kingdom shunned you out....")
        time.sleep(3)
        print("")
        print("Leomarc..")
        time.sleep(5)
        print("")
        print("With tears endlessly running down your eyes from the sight of the Kingdom currently being demolished..")
        time.sleep(4)
        print("A man carrying an instrument, with a sad and silent Gabgab behind him, calls out to you..")
        time.sleep(4)
        print("")
        print("????: I'm sorry",name,"but it's too late")
        time.sleep(3)
        print("????: I'm revered as the strongest bard on all of the lands and yet...")
        time.sleep(3)
        print("????: I could do nothing against them...")
        time.sleep(3)
        print("????: The wyverns...")
        time.sleep(3)
        print("????: there are too many of them.")
        
def displaythird():
    print("")
    print("CHAPTER THREE: Abduction")
    print("Next update!")












playplay = "Yes"
while playplay == "Yes" or playplay == "yes" or playplay == "Y" or playplay == "y":
    print("Welcome to 'Vengeance of the Sun' by Leomarc")
    print("You get to read a story about a great adventurer's quest on avenging a friend..")
    print("But this story isn't fixed as your decisions, player, would constantly be molding the ending you may witness.")
    time.sleep(12)
    print("Let's Start!!!! Warning: Choices Matter!!")
    print("")
    time.sleep(4)
    name = str(input("What's your name adventurer? :"))
    health = random.randint(100,120)
    coins = random.randint(200,1000)
    displayfirst()
    choice1 = choosepath1()
    checkpath1(choice1)
    time.sleep(8)
    displaysecond()
    choice2 = choosepath2()
    checkpath2(choice2)
    time.sleep(8)
    displaythird()











    playplay = input("Wanna play again or what? (Yes or Y): ")
